### ISSUE TITLE
iedit fails in c++ code if GTAGS files are present

### ISSUE THREAD

**Issue by Lecrapouille** [victorhge/iedit#80]
Hi !

In a c++ code (not tested with other language), iedit-mode fails replacing code if GTAGS, GPATH, GRTAGS are present (in my case they are located at the root of my c++ project). Some words are partially replaced (while well highlighted), others correctly replaced. When I removed these gtags files, iedit works very well.

~~Note: you have to restart emacs to get the issue after creating/removing gtags files.~~

Some info if needed: 
* my configuration is https://github.com/Lecrapouille/DotEmacs
* I binded iedit-mode with the F11 key
* I binded gtags with the F1 key. This will create gtags files
* For having gtags you have to do something like `sudo apt-get install global`

**Comment by victorhge** [comment]
I don't have the problem in Emacs24.5.  It looks like a problem of Emacs 25.
The workaround is to disable  ggtags-highlight-tag mode.

**Comment by Lecrapouille** [comment]
I have not tried with Emacs 24.5 I’ll give a try.

**Comment by victorhge** [comment]
Two factors：
1. A commit of Emacs， modification-hooks might not be run in some cases: 
http://git.savannah.gnu.org/cgit/emacs.git/commit/src?id=564d811725596f15ecf543777e11504b47d2af86

2. In ggtags, an overlay is deleted in the overlay's modification-hooks:
https://github.com/leoliu/ggtags/blob/eec392d2d639030c5a51bce8431f2815ad8e7bc5/ggtags.el#L2306

Deleted overlay ceases to be attached to the buffer.  If the buffer of the first overlay in the saved array doesn't  match the current buffer, then all the modification hooks will not be run in this buffer.

iedit-mode depends on the overlay's modification hooks.  So you see iedit-mode does not work if the two factors play together. 

The problem can be solved in Emacs or ggtags.  But I think it should be fixed in Emacs C code.  Before it is done,  the best thing you can do is to disable ggtags-highlight-tag mode.
